In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('creditCardFraud_28011964_120214.csv')

In [3]:
df

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,50000,1,2,1,57,-1,0,-1,0,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0
1,50000,1,1,2,37,0,0,0,0,0,...,19394,19619,20024,2500,1815,657,1000,1000,800,0
2,500000,1,1,2,29,0,0,0,0,0,...,542653,483003,473944,55000,40000,38000,20239,13750,13770,0
3,100000,2,2,2,23,0,-1,-1,0,0,...,221,-159,567,380,601,0,581,1687,1542,0
4,140000,2,3,1,28,0,0,2,0,0,...,12211,11793,3719,3329,0,432,1000,1000,1000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,100000,1,2,1,29,0,0,0,0,-1,...,-2618,95748,101299,3320,5000,0,100000,7186,0,0
997,200000,2,2,1,28,0,0,0,0,0,...,97041,103541,3632,5000,2000,89000,6500,91,1504,0
998,90000,2,2,1,40,-1,-1,-1,-1,-1,...,657,1332,780,0,2806,2256,2274,780,0,0
999,360000,1,1,2,36,1,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,1
1000,150000,2,3,2,30,-2,-2,-2,-2,-2,...,2527,0,0,9664,3420,2612,0,0,0,1

In [5]:
df.head(15)

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,50000,1,2,1,57,-1,0,-1,0,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0
1,50000,1,1,2,37,0,0,0,0,0,...,19394,19619,20024,2500,1815,657,1000,1000,800,0
2,500000,1,1,2,29,0,0,0,0,0,...,542653,483003,473944,55000,40000,38000,20239,13750,13770,0
3,100000,2,2,2,23,0,-1,-1,0,0,...,221,-159,567,380,601,0,581,1687,1542,0
4,140000,2,3,1,28,0,0,2,0,0,...,12211,11793,3719,3329,0,432,1000,1000,1000,0
5,20000,1,3,2,35,-2,-2,-2,-2,-1,...,0,13007,13912,0,0,0,13007,1122,0,0
6,200000,2,3,2,34,0,0,2,0,0,...,2513,1828,3731,2306,12,50,300,3738,66,0
7,260000,2,1,2,51,-1,-1,-1,-1,-1,...,8517,22287,13668,21818,9966,8583,22301,0,3640,0
8,630000,2,2,2,41,-1,0,-1,-1,-1,...,6500,6500,2870,1000,6500,6500,6500,2870,0,0
9,70000,1,2,2,30,1,2,2,0,0,...,66782,36137,36894,3200,0,3000,3000,1500,0,1
10,250000,1,1,2,29,0,0,0,0,0,...,59696,56875,55512,3000,3000,3000,3000,3000,3000,0
11,50000,2,3,3,23,1,2,0,0,0,...,28771,29531,30211,0,1500,1100,1200,1300,1100,0
12,20000,1,1,2,24,0,0,2,2,2,...,18338,17905,19104,3200,0,1500,0,1650,0,1
13,320000,1,1,1,49,0,0,0,-1,-1,...,70074,5856,195599,10358,10000,75940,20000,195599,50000,0
14,360000,2,1,1,49,1,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0

In [6]:
df.columns

Index(['LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0', 'PAY_2',
       'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001 entries, 0 to 1000
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   LIMIT_BAL                   1001 non-null   int64
 1   SEX                         1001 non-null   int64
 2   EDUCATION                   1001 non-null   int64
 3   MARRIAGE                    1001 non-null   int64
 4   AGE                         1001 non-null   int64
 5   PAY_0                       1001 non-null   int64
 6   PAY_2                       1001 non-null   int64
 7   PAY_3                       1001 non-null   int64
 8   PAY_4                       1001 non-null   int64
 9   PAY_5                       1001 non-null   int64
 10  PAY_6                       1001 non-null   int64
 11  BILL_AMT1                   1001 non-null   int64
 12  BILL_AMT2                   1001 non-null   int64
 13  BILL_AMT3                   1001 non-null   int64
 14  BILL_AMT4                   1001 non-null   int64
 15  BILL_AMT5                   1001 non-null   int64
 16  BILL_AMT6                   1001 non-null   int64
 17  PAY_AMT1                    1001 non-null   int64
 18  PAY_AMT2                    1001 non-null   int64
 19  PAY_AMT3                    1001 non-null   int64
 20  PAY_AMT4                    1001 non-null   int64
 21  PAY_AMT5                    1001 non-null   int64
 22  PAY_AMT6                    1001 non-null   int64
 23  default payment next month  1001 non-null   int64
dtypes: int64(24)
memory usage: 187.8 KB

In [8]:
df.isnull().sum()

LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default payment next month    0
dtype: int64

In [9]:
df.describe()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
count,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,...,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000,1001.000000
mean,167532.467532,1.589411,1.776224,1.604396,34.945055,-0.004995,-0.161838,-0.164835,-0.283716,-0.283716,...,40748.408591,39078.666334,38012.011988,5382.339660,5051.400599,4176.149850,4671.488511,5331.049950,5090.704296,0.213786
std,130587.921320,0.492187,0.750916,0.532298,9.219760,1.173446,1.228732,1.262459,1.184662,1.170224,...,68206.929510,63108.238729,63074.415024,12180.755275,15626.153184,10514.647502,13269.943983,16812.536877,23658.888052,0.410183
min,10000.000000,1.000000,1.000000,0.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,...,-3684.000000,-28335.000000,-339603.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,50000.000000,1.000000,1.000000,1.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,1423.000000,1206.000000,830.000000,1000.000000,390.000000,228.000000,148.000000,189.000000,0.000000,0.000000
50%,140000.000000,2.000000,2.000000,2.000000,33.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,17710.000000,17580.000000,15846.000000,2184.000000,1710.000000,1206.000000,1398.000000,1306.000000,1250.000000,0.000000
75%,240000.000000,2.000000,2.000000,2.000000,41.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,48851.000000,46404.000000,46557.000000,5090.000000,4500.000000,3720.000000,4000.000000,3745.000000,3784.000000,0.000000
max,700000.000000,2.000000,6.000000,3.000000,75.000000,8.000000,7.000000,7.000000,7.000000,7.000000,...,628699.000000,484612.000000,473944.000000,199646.000000,285138.000000,133657.000000,188840.000000,195599.000000,528666.000000,1.000000

In [10]:
from pandas_profiling import ProfileReport

ModuleNotFoundError: No module named 'pandas_profiling'

In [27]:
profile=ProfileReport(df,title="Pandas Profiling Report ")

NameError: name 'ProfileReport' is not defined

In [28]:
profile.to_widgets()

NameError: name 'profile' is not defined

In [11]:
X=df.drop(labels=["default payment next month"],axis=1)

In [12]:
X

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
0,50000,1,2,1,57,-1,0,-1,0,0,...,35835,20940,19146,19131,2000,36681,10000,9000,689,679
1,50000,1,1,2,37,0,0,0,0,0,...,57608,19394,19619,20024,2500,1815,657,1000,1000,800
2,500000,1,1,2,29,0,0,0,0,0,...,445007,542653,483003,473944,55000,40000,38000,20239,13750,13770
3,100000,2,2,2,23,0,-1,-1,0,0,...,601,221,-159,567,380,601,0,581,1687,1542
4,140000,2,3,1,28,0,0,2,0,0,...,12108,12211,11793,3719,3329,0,432,1000,1000,1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,100000,1,2,1,29,0,0,0,0,-1,...,67782,-2618,95748,101299,3320,5000,0,100000,7186,0
997,200000,2,2,1,28,0,0,0,0,0,...,8441,97041,103541,3632,5000,2000,89000,6500,91,1504
998,90000,2,2,1,40,-1,-1,-1,-1,-1,...,1114,657,1332,780,0,2806,2256,2274,780,0
999,360000,1,1,2,36,1,-2,-2,-2,-2,...,0,0,0,0,0,0,0,0,0,0
1000,150000,2,3,2,30,-2,-2,-2,-2,-2,...,3420,2527,0,0,9664,3420,2612,0,0,0

In [13]:
y=df['default payment next month']

In [14]:
y

0       0
1       0
2       0
3       0
4       0
       ..
996     0
997     0
998     0
999     1
1000    1
Name: default payment next month, Length: 1001, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=50)

In [20]:
X_train

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6
492,200000,2,3,2,47,0,0,0,0,0,...,194449,196814,200526,198717,7521,7000,7000,7128,8000,7100
210,470000,1,2,2,27,2,2,2,2,0,...,307843,479978,305145,309959,13000,11001,0,10484,10838,10367
220,50000,2,3,2,37,1,3,2,0,0,...,49205,30394,30249,29957,0,24,1500,1000,1201,30592
458,290000,2,2,2,26,0,0,0,-1,-1,...,100000,3015,23473,1448,80000,3000,3015,23473,1148,4900
720,80000,2,2,2,34,0,0,0,2,2,...,28783,30003,29385,31401,2000,2338,2000,0,2500,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,10000,1,2,2,27,0,0,2,0,0,...,9560,9901,9963,10182,3507,0,500,370,393,700
109,100000,2,1,2,24,0,0,0,0,0,...,54477,56076,60100,59713,2000,2677,3076,5080,3000,2033
907,500000,1,1,2,32,-1,0,0,0,0,...,293177,274539,253443,253671,25016,20018,10000,79377,52778,10000
480,100000,2,2,1,43,-1,-1,-1,-1,-1,...,574,556,2306,2562,1709,574,556,2306,2562,2111
688,200000,2,2,1,29,2,0,0,0,0,...,132144,119136,122211,125021,6163,4530,4500,5000,5000,5000

In [30]:
columns_to_drop=['Sex','Education','Marriage','Age']

In [39]:
# if all(col in df.columns for col in columns_to_drop):
X_train_new= X_train.drop(columns=columns_to_drop, axis=1)

KeyError: "['Sex', 'Education', 'Marriage', 'Age'] not found in axis"

In [38]:
X_train_new

NameError: name 'X_train_new' is not defined

In [17]:
##Preprocessing steps

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
train_scale=StandardScaler()

In [38]:
test_scale=StandardScaler()

In [39]:
X_train_scale=train_scale.fit_transform(X_train)

In [40]:
X_test_scale=train_scale.transform(X_test)

In [41]:
from sklearn.naive_bayes import GaussianNB
clf=GaussianNB()
clf.fit(X_train_scale,y_train)

GaussianNB()

In [42]:
y_pred=clf.predict(X_test_scale)

In [43]:
y_pred

array([1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0], dtype=int64)

In [44]:
from sklearn.metrics import accuracy_score

In [45]:
print(accuracy_score(y_pred,y_test))

0.6972111553784861

In [46]:
from sklearn.model_selection import GridSearchCV

In [47]:
param_grid={"var_smoothing":[1e-9,0.1,0.001,0.5,0.05,0.01,1e-8,1e-7,1e-6,1e-10,1e-11]}

In [48]:
cl=GridSearchCV(clf,param_grid=param_grid,verbose=3,cv=10)

In [49]:
cl.fit(X_train_scale,y_train)

Fitting 10 folds for each of 11 candidates, totalling 110 fits
[CV 1/10] END ..............var_smoothing=1e-09;, score=0.707 total time=   0.0s
[CV 2/10] END ..............var_smoothing=1e-09;, score=0.747 total time=   0.0s
[CV 3/10] END ..............var_smoothing=1e-09;, score=0.667 total time=   0.0s
[CV 4/10] END ..............var_smoothing=1e-09;, score=0.733 total time=   0.0s
[CV 5/10] END ..............var_smoothing=1e-09;, score=0.800 total time=   0.0s
[CV 6/10] END ..............var_smoothing=1e-09;, score=0.693 total time=   0.0s
[CV 7/10] END ..............var_smoothing=1e-09;, score=0.720 total time=   0.0s
[CV 8/10] END ..............var_smoothing=1e-09;, score=0.760 total time=   0.0s
[CV 9/10] END ..............var_smoothing=1e-09;, score=0.800 total time=   0.0s
[CV 10/10] END .............var_smoothing=1e-09;, score=0.667 total time=   0.0s
[CV 1/10] END ................var_smoothing=0.1;, score=0.720 total time=   0.0s
[CV 2/10] END ................var_smoothing=0.1;, score=0.733 total time=   0.0s
[CV 3/10] END ................var_smoothing=0.1;, score=0.747 total time=   0.0s
[CV 4/10] END ................var_smoothing=0.1;, score=0.827 total time=   0.0s
[CV 5/10] END ................var_smoothing=0.1;, score=0.773 total time=   0.0s
[CV 6/10] END ................var_smoothing=0.1;, score=0.760 total time=   0.0s
[CV 7/10] END ................var_smoothing=0.1;, score=0.800 total time=   0.0s
[CV 8/10] END ................var_smoothing=0.1;, score=0.747 total time=   0.0s
[CV 9/10] END ................var_smoothing=0.1;, score=0.773 total time=   0.0s
[CV 10/10] END ...............var_smoothing=0.1;, score=0.707 total time=   0.0s
[CV 1/10] END ..............var_smoothing=0.001;, score=0.707 total time=   0.0s
[CV 2/10] END ..............var_smoothing=0.001;, score=0.747 total time=   0.0s
[CV 3/10] END ..............var_smoothing=0.001;, score=0.680 total time=   0.0s
[CV 4/10] END ..............var_smoothing=0.001;, score=0.733 total time=   0.0s
[CV 5/10] END ..............var_smoothing=0.001;, score=0.800 total time=   0.0s
[CV 6/10] END ..............var_smoothing=0.001;, score=0.693 total time=   0.0s
[CV 7/10] END ..............var_smoothing=0.001;, score=0.720 total time=   0.0s
[CV 8/10] END ..............var_smoothing=0.001;, score=0.760 total time=   0.0s
[CV 9/10] END ..............var_smoothing=0.001;, score=0.800 total time=   0.0s
[CV 10/10] END .............var_smoothing=0.001;, score=0.667 total time=   0.0s
[CV 1/10] END ................var_smoothing=0.5;, score=0.787 total time=   0.0s
[CV 2/10] END ................var_smoothing=0.5;, score=0.733 total time=   0.0s
[CV 3/10] END ................var_smoothing=0.5;, score=0.840 total time=   0.0s
[CV 4/10] END ................var_smoothing=0.5;, score=0.813 total time=   0.0s
[CV 5/10] END ................var_smoothing=0.5;, score=0.760 total time=   0.0s
[CV 6/10] END ................var_smoothing=0.5;, score=0.773 total time=   0.0s
[CV 7/10] END ................var_smoothing=0.5;, score=0.813 total time=   0.0s
[CV 8/10] END ................var_smoothing=0.5;, score=0.760 total time=   0.0s
[CV 9/10] END ................var_smoothing=0.5;, score=0.760 total time=   0.0s
[CV 10/10] END ...............var_smoothing=0.5;, score=0.773 total time=   0.0s
[CV 1/10] END ...............var_smoothing=0.05;, score=0.720 total time=   0.0s
[CV 2/10] END ...............var_smoothing=0.05;, score=0.773 total time=   0.0s
[CV 3/10] END ...............var_smoothing=0.05;, score=0.720 total time=   0.0s
[CV 4/10] END ...............var_smoothing=0.05;, score=0.800 total time=   0.0s
[CV 5/10] END ...............var_smoothing=0.05;, score=0.813 total time=   0.0s
[CV 6/10] END ...............var_smoothing=0.05;, score=0.747 total time=   0.0s
[CV 7/10] END ...............var_smoothing=0.05;, score=0.773 total time=   0.0s
[CV 8/10] END ...............var_smoothing=0.05;, score=0.747 total time=   0.0s
[CV 9/10] END ...............var_smoothing=0.05;, score=0.800 total time=   0.0s
[CV 10/10] END ..............var_smoothing=0.05;, score=0.680 total time=   0.0s
[CV 1/10] END ...............var_smoothing=0.01;, score=0.707 total time=   0.0s
[CV 2/10] END ...............var_smoothing=0.01;, score=0.747 total time=   0.0s
[CV 3/10] END ...............var_smoothing=0.01;, score=0.680 total time=   0.0s
[CV 4/10] END ...............var_smoothing=0.01;, score=0.747 total time=   0.0s
[CV 5/10] END ...............var_smoothing=0.01;, score=0.800 total time=   0.0s
[CV 6/10] END ...............var_smoothing=0.01;, score=0.680 total time=   0.0s
[CV 7/10] END ...............var_smoothing=0.01;, score=0.720 total time=   0.0s
[CV 8/10] END ...............var_smoothing=0.01;, score=0.760 total time=   0.0s
[CV 9/10] END ...............var_smoothing=0.01;, score=0.800 total time=   0.0s
[CV 10/10] END ..............var_smoothing=0.01;, score=0.680 total time=   0.0s
[CV 1/10] END ..............var_smoothing=1e-08;, score=0.707 total time=   0.0s
[CV 2/10] END ..............var_smoothing=1e-08;, score=0.747 total time=   0.0s
[CV 3/10] END ..............var_smoothing=1e-08;, score=0.667 total time=   0.0s
[CV 4/10] END ..............var_smoothing=1e-08;, score=0.733 total time=   0.0s
[CV 5/10] END ..............var_smoothing=1e-08;, score=0.800 total time=   0.0s
[CV 6/10] END ..............var_smoothing=1e-08;, score=0.693 total time=   0.0s
[CV 7/10] END ..............var_smoothing=1e-08;, score=0.720 total time=   0.0s
[CV 8/10] END ..............var_smoothing=1e-08;, score=0.760 total time=   0.0s
[CV 9/10] END ..............var_smoothing=1e-08;, score=0.800 total time=   0.0s
[CV 10/10] END .............var_smoothing=1e-08;, score=0.667 total time=   0.0s
[CV 1/10] END ..............var_smoothing=1e-07;, score=0.707 total time=   0.0s
[CV 2/10] END ..............var_smoothing=1e-07;, score=0.747 total time=   0.0s
[CV 3/10] END ..............var_smoothing=1e-07;, score=0.667 total time=   0.0s
[CV 4/10] END ..............var_smoothing=1e-07;, score=0.733 total time=   0.0s
[CV 5/10] END ..............var_smoothing=1e-07;, score=0.800 total time=   0.0s
[CV 6/10] END ..............var_smoothing=1e-07;, score=0.693 total time=   0.0s
[CV 7/10] END ..............var_smoothing=1e-07;, score=0.720 total time=   0.0s

[CV 8/10] END ..............var_smoothing=1e-07;, score=0.760 total time=   0.0s
[CV 9/10] END ..............var_smoothing=1e-07;, score=0.800 total time=   0.0s
[CV 10/10] END .............var_smoothing=1e-07;, score=0.667 total time=   0.0s
[CV 1/10] END ..............var_smoothing=1e-06;, score=0.707 total time=   0.0s
[CV 2/10] END ..............var_smoothing=1e-06;, score=0.747 total time=   0.0s
[CV 3/10] END ..............var_smoothing=1e-06;, score=0.667 total time=   0.0s
[CV 4/10] END ..............var_smoothing=1e-06;, score=0.733 total time=   0.0s
[CV 5/10] END ..............var_smoothing=1e-06;, score=0.800 total time=   0.0s
[CV 6/10] END ..............var_smoothing=1e-06;, score=0.693 total time=   0.0s
[CV 7/10] END ..............var_smoothing=1e-06;, score=0.720 total time=   0.0s
[CV 8/10] END ..............var_smoothing=1e-06;, score=0.760 total time=   0.0s
[CV 9/10] END ..............var_smoothing=1e-06;, score=0.800 total time=   0.0s
[CV 10/10] END .............var_smoothing=1e-06;, score=0.667 total time=   0.0s
[CV 1/10] END ..............var_smoothing=1e-10;, score=0.707 total time=   0.0s
[CV 2/10] END ..............var_smoothing=1e-10;, score=0.747 total time=   0.0s
[CV 3/10] END ..............var_smoothing=1e-10;, score=0.667 total time=   0.0s
[CV 4/10] END ..............var_smoothing=1e-10;, score=0.733 total time=   0.0s
[CV 5/10] END ..............var_smoothing=1e-10;, score=0.800 total time=   0.0s
[CV 6/10] END ..............var_smoothing=1e-10;, score=0.693 total time=   0.0s
[CV 7/10] END ..............var_smoothing=1e-10;, score=0.720 total time=   0.0s
[CV 8/10] END ..............var_smoothing=1e-10;, score=0.760 total time=   0.0s
[CV 9/10] END ..............var_smoothing=1e-10;, score=0.800 total time=   0.0s
[CV 10/10] END .............var_smoothing=1e-10;, score=0.667 total time=   0.0s
[CV 1/10] END ..............var_smoothing=1e-11;, score=0.707 total time=   0.0s
[CV 2/10] END ..............var_smoothing=1e-11;, score=0.747 total time=   0.0s
[CV 3/10] END ..............var_smoothing=1e-11;, score=0.667 total time=   0.0s
[CV 4/10] END ..............var_smoothing=1e-11;, score=0.733 total time=   0.0s
[CV 5/10] END ..............var_smoothing=1e-11;, score=0.800 total time=   0.0s
[CV 6/10] END ..............var_smoothing=1e-11;, score=0.693 total time=   0.0s
[CV 7/10] END ..............var_smoothing=1e-11;, score=0.720 total time=   0.0s
[CV 8/10] END ..............var_smoothing=1e-11;, score=0.760 total time=   0.0s
[CV 9/10] END ..............var_smoothing=1e-11;, score=0.800 total time=   0.0s
[CV 10/10] END .............var_smoothing=1e-11;, score=0.667 total time=   0.0s

GridSearchCV(cv=10, estimator=GaussianNB(),
             param_grid={'var_smoothing': [1e-09, 0.1, 0.001, 0.5, 0.05, 0.01,
                                           1e-08, 1e-07, 1e-06, 1e-10, 1e-11]},
             verbose=3)

In [50]:
cl.best_params_

{'var_smoothing': 0.5}

In [51]:
y_test_pred=cl.predict(X_test_scale)

In [52]:
print(accuracy_score(y_test,y_test_pred))

0.8007968127490039

In [53]:
y_test_pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [54]:
cl.cv_results_

{'mean_fit_time': array([0.0040652 , 0.00303767, 0.0023742 , 0.0026196 , 0.00289505,
        0.00234437, 0.00244699, 0.00297792, 0.00307207, 0.00402856,
        0.00433965]),
 'std_fit_time': array([0.00158054, 0.00050289, 0.00054147, 0.00066715, 0.00082228,
        0.0004471 , 0.00050882, 0.00043154, 0.00061128, 0.00096552,
        0.00128873]),
 'mean_score_time': array([0.00298901, 0.0017314 , 0.00165489, 0.00195243, 0.00189171,
        0.00177286, 0.00194995, 0.00178685, 0.00209501, 0.00271633,
        0.00251093]),
 'std_score_time': array([0.00135229, 0.00068826, 0.00061521, 0.00090061, 0.00039465,
        0.00036706, 0.00057353, 0.0005606 , 0.00054572, 0.00073335,
        0.00064153]),
 'param_var_smoothing': masked_array(data=[1e-09, 0.1, 0.001, 0.5, 0.05, 0.01, 1e-08, 1e-07,
                    1e-06, 1e-10, 1e-11],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'var_smoothing': 1e-09},
  {'var_smoothing': 0.1},
  {'var_smoothing': 0.001},
  {'var_smoothing': 0.5},
  {'var_smoothing': 0.05},
  {'var_smoothing': 0.01},
  {'var_smoothing': 1e-08},
  {'var_smoothing': 1e-07},
  {'var_smoothing': 1e-06},
  {'var_smoothing': 1e-10},
  {'var_smoothing': 1e-11}],
 'split0_test_score': array([0.70666667, 0.72      , 0.70666667, 0.78666667, 0.72      ,
        0.70666667, 0.70666667, 0.70666667, 0.70666667, 0.70666667,
        0.70666667]),
 'split1_test_score': array([0.74666667, 0.73333333, 0.74666667, 0.73333333, 0.77333333,
        0.74666667, 0.74666667, 0.74666667, 0.74666667, 0.74666667,
        0.74666667]),
 'split2_test_score': array([0.66666667, 0.74666667, 0.68      , 0.84      , 0.72      ,
        0.68      , 0.66666667, 0.66666667, 0.66666667, 0.66666667,
        0.66666667]),
 'split3_test_score': array([0.73333333, 0.82666667, 0.73333333, 0.81333333, 0.8       ,
        0.74666667, 0.73333333, 0.73333333, 0.73333333, 0.73333333,
        0.73333333]),
 'split4_test_score': array([0.8       , 0.77333333, 0.8       , 0.76      , 0.81333333,
        0.8       , 0.8       , 0.8       , 0.8       , 0.8       ,
        0.8       ]),
 'split5_test_score': array([0.69333333, 0.76      , 0.69333333, 0.77333333, 0.74666667,
        0.68      , 0.69333333, 0.69333333, 0.69333333, 0.69333333,
        0.69333333]),
 'split6_test_score': array([0.72      , 0.8       , 0.72      , 0.81333333, 0.77333333,
        0.72      , 0.72      , 0.72      , 0.72      , 0.72      ,
        0.72      ]),
 'split7_test_score': array([0.76      , 0.74666667, 0.76      , 0.76      , 0.74666667,
        0.76      , 0.76      , 0.76      , 0.76      , 0.76      ,
        0.76      ]),
 'split8_test_score': array([0.8       , 0.77333333, 0.8       , 0.76      , 0.8       ,
        0.8       , 0.8       , 0.8       , 0.8       , 0.8       ,
        0.8       ]),
 'split9_test_score': array([0.66666667, 0.70666667, 0.66666667, 0.77333333, 0.68      ,
        0.68      , 0.66666667, 0.66666667, 0.66666667, 0.66666667,
        0.66666667]),
 'mean_test_score': array([0.72933333, 0.75866667, 0.73066667, 0.78133333, 0.75733333,
        0.732     , 0.72933333, 0.72933333, 0.72933333, 0.72933333,
        0.72933333]),
 'std_test_score': array([0.04582091, 0.03448671, 0.04414119, 0.0305214 , 0.04035399,
        0.044     , 0.04582091, 0.04582091, 0.04582091, 0.04582091,
        0.04582091]),
 'rank_test_score': array([6, 2, 5, 1, 3, 4, 6, 6, 6, 6, 6])}

In [55]:
pip install xgboost

Requirement already satisfied: xgboost in d:\vikalpsensor\denv\lib\site-packages (1.6.2)
Requirement already satisfied: numpy in d:\vikalpsensor\denv\lib\site-packages (from xgboost) (1.24.4)
Requirement already satisfied: scipy in d:\vikalpsensor\denv\lib\site-packages (from xgboost) (1.10.1)
Note: you may need to restart the kernel to use updated packages.

In [56]:
from xgboost import XGBClassifier

In [57]:
xgb=XGBClassifier()

In [58]:
xgb.fit(X_train_scale,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [59]:
y_pred_xgb=xgb.predict(X_test_scale)

In [60]:
accuracy_score(y_pred_xgb,y_test)

0.7689243027888446

In [61]:
param_grid_xgboost={'n_estimators':[50,100,130],
                   'max_depth':range(3,11,1),
                   'random_state':[0,50,100]}

In [62]:
gid=GridSearchCV(XGBClassifier(objective='binary:logistic'),param_grid_xgboost,verbose=3,cv=5,n_jobs=-1)

In [63]:
gid.fit(X_train_scale,y_train)

Fitting 5 folds for each of 72 candidates, totalling 360 fits

GridSearchCV(cv=5,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     gamma=None, gpu_id=None, grow_policy=None,
                                     importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None, max_bin=None,
                                     max_ca...t=None,
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     n_estimators=100, n_jobs=None,
                                     num_parallel_tree=None, predictor=None,
                                     random_state=None, reg_alpha=None,
                                     reg_lambda=None, ...),
             n_jobs=-1,
             param_grid={'max_depth': range(3, 11),
                         'n_estimators': [50, 100, 130],
                         'random_state': [0, 50, 100]},
             verbose=3)

In [64]:
gid.best_params_

{'max_depth': 4, 'n_estimators': 100, 'random_state': 0}

In [65]:
gid.best_estimator_

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=4, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [66]:
y_pred_xgboost=gid.predict(X_test_scale)

In [67]:
accuracy_score(y_test,y_pred_xgboost)

0.7768924302788844

In [68]:
import pickle

In [69]:
pickle.dump(gid,open("creditcard.pkl",'wb'))

In [70]:
w=pickle.load(open("creditcard.pkl",'rb'))

In [71]:
w.predict(X_test_scale)

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0])

In [72]:
import pymongo

In [73]:
uri="mongodb+srv://<username>:vikalp026var@cluster0.r31hq0n.mongodb.net/?retryWrites=true&w=majority"

In [74]:
client=pymongo.MongoClient(uri)

In [75]:
df=client["Credit_Card_data"]

In [76]:
collections=df["Collection"]

In [80]:
import json

In [85]:
import pymongo 
import pandas as pd 
import json 
uri="mongodb+srv://vikalp026varshney:Vikalp026var@cluster0.r31hq0n.mongodb.net/?retryWrites=true&w=majority"
client=pymongo.MongoClient(uri)
DATABASE_NAME="Credit_Card"
COLLECTION_NAME="collection"
df=pd.read_csv(r"D:\Credit_Card_Fraud_Detection\artifacts\creditCardFraud_28011964_120214.csv")
json_record=list(json.loads(df.T.to_json()).values())
client[DATABASE_NAME][COLLECTION_NAME].insert_many(json_record)
print("Succesfully insert into Mongodb")

Succesfully insert into Mongodb

In [84]:
collections.insert_many(json_file)

TypeError: document must be an instance of dict, bson.son.SON, bson.raw_bson.RawBSONDocument, or a type that inherits from collections.MutableMapping